### ISSUE TITLE
Please add the VM credentials to its Wiki Page

### ISSUE THREAD

**Issue by Morgon** [droboports/droboports.github.io#1]
https://github.com/droboports/droboports.github.io/wiki/Setting-up-a-VM#creating-the-vm

After reviewing the original SDK package, as pointed out by 'jasonob', I do see the pre-configured credentials are 'drobo/drobo'. Please add this to the wiki to reduce confusion. It's the only place I was able to locate those access details.

**Comment by ricardopadilha** [comment]
Thanks for the heads up. The wiki page has been updated.
